---
title: "activity3"
output: html_fragment
---

A sample's location in $n$-dimensional space is defined by its position on each of the $n$ available axes. These positions are called scores and a sample's scores change in value as we rotate the axes. The figure on the right shows a data set that has eight samples (the black circles) and two variables (the magenta and light blue lines). The small number of samples ensures the figure is uncluttered, so individual points are easy to see, and using just two variables allows you to fully view the data set within your screen's limit of two-dimensions. A slider allows you to rotate the axes in space, with the angle of rotation defined relative to the original axes. As a visual reference, when you rotate the axes, the original axes are preserved and displayed as dashed lines.

**Exercise 1**. Leave the rotation angle at $0°$ and describe in words the position of the eight samples relative to the original axes. Which of the two axes---the one for variable 1 or the one for variable 2---best aligns with the eight samples? Explain how you reached your decision.

**Exercise 2**. A sample's scores are determined by drawing a perpendicular line from the sample to each of the two original or rotated axes, as seen by the two dashed dark blue lines attached to the sample on the figure's lower left. The small magenta and blue circles show the location of these perpendicular projections on the axes. The scores for this sample when the angle of rotation is $0°$ are $-3.96$ for variable 1 and $-8.31$ for variable 2. Convince yourself that these are the correct scores.

**Exercise 3**. Use the slider to rotate the axes by $15°$, $30°$, $45°$, $60°$, $75°$, and $90°$, and for each estimate the scores for the sample from Exercise 2. As you rotate the axes, what happens to this sample's scores? Which of the rotated axes contains the most information about the signal---this is the first principal component axis---and which contains the most information about noise---and is the second principal component axus?


