---
title: "activity4"
output: html_fragment
---
On the previous tab you identified the first principal component axis by rotating the axes until one of them was reasonably well-aligned with the eight samples. The lack of a quantitative measure of "reasonably well-aligned," means you identified the first principal component axis by estimating the angle of rotation that best aligned one of the rotated axes. With just eight samples, visually identifying the first principal component axis is not a challenge. Imagine, however, using this approach to find the first principal component axis for a data set with hundreds of samples, many of which will overlap each other.  

**Exercise 1**. Earlier we described the first principal component axis as having the greatest variability in the scores of the sample. We can report this variability quantitatively by using the scores to calculate a variance. For example, when the angle of rotation is $0°$, the eight samples have scores on the axis for variable 1 of 

$$2.66 \quad -1.23 \quad 0.25 \quad -3.86 \quad 4.94 \quad 0.25 \quad 2.96 \quad -3.96$$

and scores on the axis for variable 2 of 

$$3.32 \quad -5.15 \quad -2.69 \quad -7.21 \quad 7.82 \quad 1.57 \quad 4.40 \quad -8.31$$

Calculate the variance for variable 1 and for variable 2, and the percent of the overall variance for each variable. Verify that your results match those on the figure on the right.

**Exercise 2**. Adjust the angle of rotation until you maximize the variance for the first principal component axis. Does this angle of rotation agree with your work on the previous tabs?




 
