---
title: "introduction"
output: html_fragment
---
$\require{mhchem}$Principal component analysis, or PCA, is an unsupervised machine learning algorithm used to find the structure of a data set---particularly one with many variables---by reducing the data set's dimensionality. 

#### What Does it Mean to Reduce a Data Set's Dimensionality?

The data on the right are from a collection of visible spectra for 80 samples that contain one or more of $\ce{Cu^{2+}}$, $\ce{Ni^{2+}}$, $\ce{Cr^{3+}}$, and $\ce{Co^{2+}}$ ions. Individual spectra were recorded at 642 wavelengths between 380.5 nm and 899.5 nm. The four samples included here are stock solutions of the individual metal ions. 

We usually display a visible spectrum by plotting absorbance on the *y*-axis and wavelength on the *x*-axis; however, we can display absorbance data in other ways. For example Figure (a) uses a single axis to report the absorbance at 809.1 nm for each of the stock solutions. Figures (b) and (c) use two or three axes to show the absorbance of each stock solution at two or three wavelengths. Each axis reports the absorbance for a distinct wavelength, or dimension. We can include axes for each of the data set's 642 wavelengths. Our goal is to find and keep the smallest number of axes that can explain the data; this is what it means to reduce a data set's dimensionality.

#### The Challenge of Working With High Dimensionality Data

Although we easily can visualize data in one, two, or three dimensions, Figure (d) reminds us that we are limited to three axes, each orthogonal to---at 90° to---the other two axes. Although we cannot simultaneously display data on 642 orthogonal axes---or even four orthogonal axes---any mathematical function that we can apply to data in three dimensions, such as rotating it around an axis, we can apply to the data in $n$-dimensional space. And, if we can reduce the meaningful dimensions to three or fewer, then we can examine the data visually as well. How we accomplish this is the focus of this learning module.
